### ISSUE TITLE
Make tiles interactive

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#1]
Specify causes and effects for tiles. Add an interactive door, where using the tile (e.g. closed door) is the cause and transforming it into another (e.g. open door) is the effect.

## Draft

```python
class Cause:
    """Cause of a tile effect."""

    """Type of the cause."""
    type: str

class Effect:
    """Tile effect."""

    """Type of the effect."""
    type: str

    async def apply(self, tile_index: int) -> None:
        """Apply the effect to the tile at *tile_index*."""

class Tile:
    """Tile effects by cause."""
    effects: dict[Cause, list[Effect]]

    async def cause(self, cause: Cause, tile_index: int) -> list[Effect]:
        """Apply the effects for a *cause* to the tile at *tile_index*."""

# Causes and effects:

class UseCause(Cause):
    """Cause of using a tile."""

    # Future reference
    """ID of the used item, if any."""
    item_id: str | None

    # Future reference
    @property
    def item(self) -> Tile | None:
        """Used item, if any."""

# Future reference
class TickCause(Cause):
    time: float

class TransformEffect(Effect):
    """Effect to transform a tile into another."""

    """ID of the target form."""
    blueprint_id: str

    @property
    def blueprint(self) -> Tile:
        """Target form."""

# Future reference
class OpenDialogEffect(Effect):
    messages: list[tuple[str, str, str]]

# Actions:

# Just in principle, for now merge with UseAction
class CauseAction(Action):
    tile_index: int

    """Caused tile effects."""
    effects: list[Effect]

class UseAction(CauseAction):
    # Future reference
    """ID of the used item, if any."""
    item_id: str | None
```

Provide interactive door and lamp tiles.

UI:

* Click / Tap: Use tile
* Highlight usable tiles in use radius

## Tasks

* [x] Implement draft
* [x] `TransformEffect`: Move to `TransformTileEffect`
* [x] `TransformTileEffect.apply()`: Test
* [x] `Tile.effects`: Type as `AnyCause` and `AnyEffect` (discriminated union)
* [x] `Tile.effects`: Serialize as key-value pairs (`@field_serializer`, `@field_validator`)
* [x] `Tile.effects`: Validate uniqueness of causes and effects (https://github.com/pydantic/pydantic-core/pull/820#issuecomment-1670475909)
* [x] `Tile.cause()`: Test
* [x] `UpdateBlueprintAction.perform()`: Check `TransformTileEffect.blueprint_id`
* [x] `game.DEFAULT_BLUEPRINTS`: Use custom IDs
* [x] `/rooms`: Handle `IndexError`
* [x] `GameElement`: Add `#updateTileElement()` utility
* [x] `GameElement`: Define `#PLAYER_REACH`
* [x] `GameElement`: Rename `.room-game-has-item` to `.room-game-equipped`
* [x] `GameElement.#findTileElementsInRadius()`: Handle edge cases
* [x] `GameElement.#use()`: Log warning for unknown effects
