### ISSUE TITLE
Authenticate players

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#16]
Authenticate players with cookies.

## Draft

```python
class Player:
    """Player of the game."""

    """Unique player ID."""
    id: str

    # Future reference (name)

    """Name or nick name."""
    name: str

class PrivatePlayer(Player):
    """Private view of the player."""

    """Authentication token."""
    token: str

    # Future reference (name)

    # PATCH /api/players/{id} -> 200 Player
    def edit(self, name: str) -> None:
        """Edit the player *name*.

        Permission: Player oneself.
        """

    # Future reference (player-rooms)

    # GET /api/players/{id}/memberships -> 200 list[MemberWithRoom]
    @property
    def memberships(self) -> list[Member]:
        """Room memberships.

        Permission: Player oneself.
        """

    def link_membership(self, member: Member) -> None:
        """Link an existing room membership *member*."""

    # Future reference (sign-in)

    """Email address. ``None`` for temporary players."""
    email: str | None

class Member(BaseModel): # type: ignore[misc]
    """Player as member of a room."""

    """Unique member ID."""
    id: str
    """Relevant player ID."""
    player_id: str
    """Current position in px."""
    position: tuple[float, float]

    @property
    def player(self) -> Player:
        """Relevant player."""

    # GET /api/rooms/{id}/actions -> 100
    async def actions(self) -> AsyncGenerator[Action, None]:
        """Stream of actions intended for the member."""

    async def publish(self, action: Action) -> None:
        """Publish an *action* to the member."""

    def with_player(self) -> MemberWithPlayer:
        """Create a copy of the member with player included."""

    # Future reference (role)

    """Relevant room ID."""
    room_id: str
    """Member role."""
    role: Literal['guest', 'resident', 'owner']
    """Current position in px.``None`` if offline."""
    position_: tuple[float, float] | None

    @property
    def room(self) -> RoomPreview:
        """Relevant room."""

    # DELETE /api/members/{id} -> 200 Member
    def leave(self) -> None:
        """Leave the room as a member.

        Permission: Player oneself.
        """

    # Future reference (player-rooms)

    def with_room(self) -> MemberWithRoom:
        """Create a copy of the member with room included."""

class MemberWithPlayer(Member): # type: ignore[misc]
    """Room member with player included."""

    @computed_field # type: ignore[misc]
    @property
    def player(self) -> Player:
        pass

class Action(BaseModel): # type: ignore[misc]
    """ID of the room member performing the action."""
    member_id: str

    @property
    def member(self) -> Member:
        """Room member performing the action."""

class WelcomeAction(Action): # type: ignore[misc]
    room: OnlineRoomWithMembers

class OnlineRoom(RoomPreview): # type: ignore[misc]
    # GET /api/rooms/{id}/members -> list[MemberWithPlayer]
    @property
    def members(self) -> Sequence[Member]:
        """Room members."""

    @asynccontextmanager
    async def enter(self) -> AsyncGenerator[Member, None]:
        """Context manager to enter the room as a member.

        On exit also exit the room again. If the player is not a resident, a guest member is created
        for the stay.
        """
        yield # type: ignore[misc]

    def with_members(self) -> OnlineRoomWithMembers:
        """Create a copy of the room with members included."""

    def link_member(self, member: Member) -> None:
        """Link an existing *member*."""

    # Future reference (role)

    """Invitation token."""
    invite: str

    # POST /api/rooms/{id}/members -> 201 Member
    def join(self, invite: str) -> Member:
        """Join the room as a member with an *invite* token."""

class OnlineRoomWithMembers(OnlineRoom): # type: ignore[misc]
    """Room with members included."""

    @computed_field # type: ignore[misc]
    @property
    def members(self) -> Sequence[MemberWithPlayer]:
        pass

class Game:
    # GET /api/players/{id} -> Player
    # Storage: players/{id}.json
    """Players by ID."""
    players: dict[str, PrivatePlayer]

    # GET /api/rooms/{id} -> OnlineRoom
    # Storage: rooms/{id}.json
    rooms: dict[str, OnlineRoom]

    def authenticate(self, token: str) -> PrivatePlayer:
        """Authenticate a player with *token*.

        If authentication fails, a :exc:`LookupError` is raised.
        """

    # Future reference (role)

    # GET /api/members/{id} -> 200 MemberWithPlayer
    # Storage: members/{id}.json
    """Room members by ID."""
    members: dict[str, Member]

    # Implementation note
    async def run(self) -> NoReturn: # type: ignore[misc]
        for path in Path('members').iterdir():
            member = Member.model_validate_json(path.read_text())
            self.members[member.id] = member
            assert isinstance(member.room, OnlineRoom)
            member.room.link_member(member)
            assert isinstance(member.player, PrivatePlayer)
            member.player.link_membership(member)

    # Future reference (sign-in)

    # POST /api/sign-ins -> 201 SignIn
    @overload
    def sign_in(self) -> PrivatePlayer:
        pass
    @overload
    def sign_in(self, email: str) -> SignIn:
        pass
    def sign_in(self, email: str | None = None) -> SignIn | PrivatePlayer:
        """Start signing in a player by *email*.

        Without *email*, create a temporary player.
        """

# Future reference (player-rooms)

class RoomPreview(BaseModel): # type: ignore[misc]
    """Preview of the room."""

    """Unique room ID."""
    id: str

class MemberWithRoom(Member): # type: ignore[misc]
    """Room member with room included."""

    @computed_field # type: ignore[misc]
    @property
    def room(self) -> RoomPreview:
        pass

# Future reference (sign-in)

class SignIn:
    """Player sign-in by email."""

    """Email address."""
    email: str
    """Authentication code."""
    code: str

    # POST /api/sign-ins/{id} -> 201 PrivatePlayer
    def finish(self, code: str) -> PrivatePlayer:
        """Finish signing in a player with an authentication *code*.

        If no player with :attr:`email` exists yet, one is created.
        """
```

## Tasks

* [x] Implement draft
* [x] `Game.sign_in()`: Use cryptographically random token
* [x] `Game.run()`: Make update robust against failures
* [x] `Game`: Add `_add_player()` utility
* [x] `Game`: Rename `_auth_map` to `_tokens`
* [x] `__main__._authenticate()`: Support WebSocket with type hints
* [x] `__main__._update_cookie()`: Set cookie attributes
