### ISSUE TITLE
Improve invite links

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#17]
Make invite links more readable and pave the way for link previews and window hash navigation.

## Draft

Invite link: `/invites/{id}`

API:

```
POST /api/rooms -> 201 OnlineRoom
GET /api/rooms/{id} -> 200 OnlineRoom
GET /api/rooms/{id}/actions -> 100
```

## Tasks

* [x] Implement draft
* [x] `GameElement.connectedCallback()`: Use `Router`
* [x] `GameElement`: Rename `#setUpRoom()` to `#initRoom()`
* [x] `server`: Generate JSON errors
* [x] `server`: Use `BaseModel` instead of `TypeAdapter`
* [x] `server`: Provide `/api/players/{id}`, `/api/rooms/{id}/members` and `/api/members/{id}`
