### ISSUE TITLE
Add window about room

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#19]
Add windows for viewing and editing room details.

Depends on #18.

## Draft

```
.-----------------------.
| Cat Colony        | X |
|-----------------------|
| Hangout for the cats. |
|-----------------------|
| Created on 1 Oct 2023 | <- Future reference
|-----------------------|
| / Edit                | <- Open editor (only visible for residents)
'-----------------------'

.--------------------------------.
| Edit Room Details | V Done | X | <- Back to about window
|--------------------------------|
| (Title)                        |
| Cat Colony                     |
|--------------------------------|
| (Description)                  |
| Hangout for the cats.          |
'--------------------------------'

* Inventory: i About Room
* Enter room and update room: Show and fade out title at the top
```

## Tasks

* [x] Implement draft
* [x] `game`: Rename `DetailsEditorElement` to `RoomEditorElement`
* [x] `GameElement`: Add `#updateRoom()` action
* [x] `core`: Add `getGame()` utility
* [x] `core`: Implement `WindowHeaderElement`
* [x] `WindowHeaderElement`: Replace `back` with `close`
