### ISSUE TITLE
Complete player tutorial

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#24]
Start the tutorial until the player has completed all lessons.

Depends on #23.

## Draft

```
.----------------------------.
| + How to Play          | X | <- Not for tutorial
|----------------------------|
| * Hold / Touch to move     |
| * Click / Tap to use items |
|----------------------------|
| Start                      | <- Only for tutorial
'----------------------------'
```

## Tasks

* [x] Implement draft
* [x] `game`: Rename `HowToPlayElement` to `HowtoElement`
* [x] `GameElement`: Rename `#onboard()` to `#completeLesson()`
* [x] `GameElement.player`: Make non-optional
