### ISSUE TITLE
Add tile effects editor

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/room#3]
Make an effects editor available from the blueprint window.

## Draft

```
.---------.    .-----------------.
| Use | - | -> | Transform   | - | <- Remove effect
|---------|    |-----------------|
| O       |    | O               | <- Edit attributes (here: select target form)
'---------'    '-----------------'

               .-----------------.
               | Open Dialog | - |
               |-----------------|
               | Meow!           |
               '-----------------'

               .--------------.
               | + Add Effect |
               '--------------'
               (Add at least one effect) <- Validation

.-------------.
| + Add Cause |
'-------------'
(Edit or remove duplicate causes)
```

## Tasks

* [x] Implement draft
* [x] `<room-effects>`: Rename to `<room-blueprint-effects>`
* [x] `<room-effects>`: Move wall input and effects button to footer
* [x] `<room-blueprint-effects>`: Shrink add buttons
* [x] `<room-effect-header>`: Use `<h3>`
* [x] `/`: Support focus tabbing for `.contextual`
* [x] `Tile`: Remove duplicate effects validation
